Squid:
  package: squid
  systemd: squid
  conf: /etc/squid/squid.conf
  default_port: 3128
TinyProxy:
  package: tinyproxy
  systemd: tinyproxy
  conf: /etc/tinyproxy/tinyproxy.conf
  default_port: 8888
Nginx-Reverse:
  package: nginx
  systemd: nginx
  conf: /etc/nginx/nginx.conf
  default_port: 80
HAProxy:
  package: haproxy
  systemd: haproxy
  conf: /etc/haproxy/haproxy.cfg
  default_port: 80
SSlh:
  package: sslh
  systemd: sslh
  conf: /etc/default/sslh
  default_port: 443
Stunnel:
  package: stunnel4
  systemd: stunnel4
  conf: /etc/stunnel/stunnel.conf
  default_port: 443
OpenVPN:
  package: openvpn
  systemd: openvpn
  conf: /etc/openvpn/server.conf
  default_port: 1194
BadVPN:
  package: badvpn
  systemd: badvpn
  conf: /etc/default/badvpn
  default_port: 7300
PPTP:
  package: pptpd
  systemd: pptpd
  conf: /etc/pptpd.conf
  default_port: 1723
SlowDNS:
  package: slowdns
  systemd: slowdns
  conf: /etc/slowdns.conf
  default_port: 53