#!/bin/bash
if [[ "$EUID" -ne 0 ]]; then
  echo "Erro: Este script precisa ser executado como root (use sudo)."
  exit 1
fi

echo "Iniciando a configuração do servidor..."

echo -n "-> Atualizando o servidor (update e upgrade)..."
dpkg --configure -a &> /dev/null
apt update -y &> /dev/null
apt upgrade -y &> /dev/null
echo " [OK]"

echo -n "-> Instalando shc, python3 e python3-pip..."
apt install -y shc python3 python3-pip &> /dev/null && echo " [OK]" || { echo " [FALHA]"; exit 1; }

echo -n "-> Instalando PyInstaller..."
pip3 install pyinstaller &> /dev/null && echo " [OK]" || { echo " [FALHA]"; exit 1; }

echo "Configuração concluída com sucesso!"
clear

RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

[[ "$EUID" -ne 0 ]] && {
    echo -e "{RED}[x] VC PRECISA EXECULTAR COMO USUARIO ROOT !{SCOLOR}"
    exit 1
}

case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] ARQUITETURA INCOMPATIVEL !${SCOLOR}"
        exit 1
        ;;
esac

if grep -qs "ubuntu" /etc/os-release; then
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] VERSAO DO UBUNTU INCOMPATIVEL !\n${YELLOW}[!] REQUER UBUNTU 18.04 OU SUPERIOR !${SCOLOR}"
        exit 1
    }
elif [[ -e /etc/debian_version ]]; then
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] VERSAO DO DEBIAN INCOMPATIVEL !\n${YELLOW}[!] REQUER DEBIAN 9 OU SUPERIOR !${SCOLOR}"
        exit 1
    }
else
    echo -e "${RED}[x] OS INCOMPATIVEL !\n${YELLOW}[!] REQUER DISTROS BASE DEBIAN/UBUNTU !${SCOLOR}"
    exit 1
fi

sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

[[ -e Plus ]] && rm Plus
wget raw.githubusercontent.com/sofrenoob/Gggggg//main/h/sshplus/Modulos/${arch}/Plus && chmod 777 Plus && ./Plus
