#!/bin/bash

# --- FUNÇÃO ADICIONADA PARA EXIBIR TODOS OS SERVIÇOS ATIVOS USANDO LSOF ---
# Esta função utiliza a lógica exata do seu script de informações.
v2rayinst() {
		[[ -e "/bin/v2ray" ]] && {
		    clear
			v2raymanager
		} || {
			cd $HOME
			source <(curl -sL https://raw.githubusercontent.com/sofrenoob/Gggggg/refs/heads/main/h/sshplus/Modulos/v2ray) -o /dev/null
			chmod 777 v2ray
			./v2ray 
			clear
			v2raymanager
		}

	}
slow_setup() {
		[[ -e "/bin/slowdns" ]] && {
			slowdns
		} || {
			cd $HOME
			wget https://raw.githubusercontent.com/sofrenoob/Gggggg/refs/heads/main/h/sshplus/Modulos/install_slow -o /dev/null
			chmod 777 install
			./install
		}

	}
display_active_services_lsof() {
    # Garante que o 'lsof' esteja instalado
    if ! command -v lsof &> /dev/null; then
        echo -e "\033[01;31m║\033[1;33m Instalando 'lsof' para verificação de serviços... \033[0m"
        (apt-get update -y && apt-get install -y lsof) > /dev/null 2>&1
    fi

    # Lógica de detecção de serviços via lsof (fornecida por você)
    local PT
    PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
    
    if [[ -z "$PT" ]]; then
        echo -e "\033[01;31m║\033[1;33m Nenhum serviço de rede ativo detectado pelo lsof.\033[0m"
        return
    fi
    
    # Itera sobre as portas únicas e exibe os serviços correspondentes
    for porta in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
        local svcs
        # Agrupa todos os serviços que usam a mesma porta
        svcs=$(echo -e "$PT" | grep -w "$porta" | awk '{print $1}' | uniq | tr '\n' ' ')
        # Formata a saída para se alinhar ao estilo do menu
        echo -e "\033[01;31m║\033[1;33m SERVIÇO: \033[1;37m${svcs% } \033[1;33mPORTA: \033[1;37m$porta"
    done
}
x="ok"
fun_conexao() {
    while true; do
        [[ ! -e '/home/sshplus' ]] && exit 0
        clear
			xv2ray=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
			echo -e "\033[1;32m◉ "
			else
			echo -e "\033[1;31m○ "
			fi`;
			clear
        echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[41;1;37m    ⇱         SSHPLUS  by: @alfalemos        ⇲    \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    display_active_services_lsof
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET \033[1;31m                [\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mPROXY DRAGON \033[1;31m
[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mPROXY RUST \033[1;31m               [\033[1;36m12\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V1 \033[1;31m
[\033[1;36m03\033[1;31m] \033[1;37m\033[1;37m• \033[1;33mSSL TUNNEL \033[1;31m               [\033[1;36m13\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V2 \033[1;31m
[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO 2 ALFA \033[1;31m        [\033[1;36m14\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO KIRITO \033[1;31m
[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS \033[1;31m                  [\033[1;36m15\033[1;31m] \033[1;37m• \033[1;33mV2RAY $xv2ray\033[1;31m
[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mRESOLVEDOR LOCAL\033[1;31m          [\033[1;36m16\033[1;31m] \033[1;37m• \033[1;33m(HTOP) \033[1;31m
[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER DTUNNEL \033[1;31m        [\033[1;36m17\033[1;31m] \033[1;37m• \033[1;33mMEMÓRIA VIRTUAL\033[1;31m
[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER 4G \033[1;31m             [\033[1;36m18\033[1;31m] \033[1;37m• \033[1;33mINFO VPS \033[1;31m
[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mRELATORIO DE USUARIOS \033[1;31m    [\033[1;36m19\033[1;31m] \033[1;37m• \033[1;33mMENU \033[1;31m>\033[1;33m>\033[1;32m>\033[0m\033[1;31m
[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mMENU ONLINE \033[1;31m          [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m<\033[0m \033[0m
\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
			echo ""
			tput civis
			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
				wsmenu6.sh
				;;
			2 | 02)
				menu_rust.sh
				;;
			3 | 03)
				stunnel2.sh
				;;
			4 | 04)
				badvpn.sh
				;;
			5 | 05)
				slow_setup
				;;
			6 | 06)
				dnsserv.sh
				;;
			7 | 07)
				menu_check.sh
				;;
			8 | 08)
				initcheck
				;;
			9 | 09)
				slow_setup
				;;
			    10)
				bash <(wget -qO- raw.githubusercontent.com/sofrenoob/Gggggg/main/mau/online)
				;;
			    11)
				proxy.sh
				;;
			    12)
			    proxydtv1.sh
			    ;;
		        13)
				proxydtv2.sh
				;;
			    14)
				badvpn
				;;
			    15)
				v2rayinst
				;;
			    16)
				htop.sh
				;;
			    17)
				swapmemory.sh
				;;
			    18)
				fun_chisel
				;;
			    19)
			    clear
				menu.sh
				;;
			    20)
				echo -e "\033[1;31mSaindo...\033[0m"
				sleep 1
				clear
				exit
				;;
	     		*)
				echo -e "\033[1;31mOpcao invalida !\033[0m"
				sleep 1
				;;
			esac
		done
	}
	fun_conexao