#!/bin/bash
clear
#--------------------------
# SCRIPT SSH-PLUS
# CANAL TELEGRAM: @ALFAINTERNET
#--------------------------

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Verifica Execução Como Root
[[ "$EUID" -ne 0 ]] && {
    echo -e "${RED}[x] VC PRECISA EXECUTAR COMO USUÁRIO ROOT !${SCOLOR}"
    exit 1
}

# - Verifica Arquitetura Compatível
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] ARQUITETURA INCOMPATÍVEL !${SCOLOR}"
        exit 1
        ;;
esac

# - Verifica OS Compatível
if lsb_release -d | grep -q "Ubuntu"; then
    os_version=$(lsb_release -r | cut -f2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] VERSÃO DO UBUNTU INCOMPATÍVEL !\n${YELLOW}[!] REQUER UBUNTU 18.04 OU SUPERIOR !${SCOLOR}"
        exit 1
    }
elif lsb_release -d | grep -q "Debian"; then
    os_version=$(lsb_release -r | cut -f2 | tr -d '.')
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] VERSÃO DO DEBIAN INCOMPATÍVEL !\n${YELLOW}[!] REQUER DEBIAN 9 OU SUPERIOR !${SCOLOR}"
        exit 1
    }
else
    echo -e "${RED}[x] OS INCOMPATÍVEL !\n${YELLOW}[!] REQUER DISTROS BASE DEBIAN/UBUNTU !${SCOLOR}"
    exit 1
fi

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Desabilita IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

# - Executa instalador
[[ -e Plus ]] && rm Plus
wget raw.githubusercontent.com/sofrenoob/Gggggg/main/s/${arch}/Plus -O Plus
if [[ ! -f Plus ]]; then
    echo -e "${RED}[x] Falha ao baixar o arquivo Plus!${SCOLOR}"
    exit 1
fi
chmod +x Plus && ./Plus
