#!/bin/bash
clear
echo "   SSH-PLUS" | figlet
echo -e " \033 By: @alfalemos"
echo -e "\E[41;1;37m      ⇱⇲         EU SOU UMA CÓPIA DA CÓPIA 😏         ⇱⇲       \E[0m\n"

echo -e " \033      AQUI TERÁ LINKS ÚTEIS PARA INSTALAÇÕES RÁPIDAS"
echo -e ""
echo -e " \033[1;37m[\033[1;31m01\033[1;37m] - \033[1;33m    "
echo -e " \033[1;37m[\033[1;31m02\033[1;37m] - \033[1;33m    "
echo -e " \033[1;37m[\033[1;31m03\033[1;37m] - \033[1;33m    "
echo -e " \033[1;37m[\033[1;31m04\033[1;37m] - \033[1;33m     "
echo -e " \033[1;37m[\033[1;31m00\033[1;37m] - \033[1;33mSAIR     "
echo ""
echo -ne "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   menu
   ;;
   2 | 02)
   clear
   menu
   ;;
   3 | 03)
   clear
   menu
   ;;
   4 | 04)
   clear
   menu
   ;;
   0 | 00)
   clear
   menu
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
done
}
#fim

